# -*- coding: utf-8 -*-
"""paper_moderation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19nP2CRaw0MBx--q_KLUKnQizmMEbbsxB

Load HuggingFace DataSet
"""

!pip install datasets
!pip install transformers

import pandas as pd
from google.colab import userdata
from datasets import load_dataset

userdata.get('HF_TOKEN')
ds = load_dataset("mlcore/arxiv-classifier", "default")

ds # title, abstract, full text

"""# BERT Tokenizer"""

from transformers import BertTokenizer
tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')

# Title
title_encodings = tokenizer.encode(ds['train']['title'][0]) # encoding first data point
print('\nTitle Encodings')
print(title_encodings)
print(tokenizer.convert_ids_to_tokens(title_encodings))

# Abstract
abstract_encodings = tokenizer.encode(ds['train']['abstract'][0])
print('\nAbstract Encodings')
print(abstract_encodings)
print(tokenizer.convert_ids_to_tokens(abstract_encodings))


# Full Text
full_text_encodings = tokenizer.encode(ds['train']['fulltext'][0])
print('\nFull Text Encodings')
print(full_text_encodings)
print(tokenizer.convert_ids_to_tokens(full_text_encodings))

"""# AutoTokenizer"""

from transformers import AutoTokenizer
tokenizer = AutoTokenizer.from_pretrained('bert-base-uncased')

# Title
title_encodings = tokenizer.encode(ds['train']['title'][0]) # encoding first data point
print('\nTitle Encodings')
print(title_encodings)
print(tokenizer.convert_ids_to_tokens(title_encodings))

# Abstract
abstract_encodings = tokenizer.encode(ds['train']['abstract'][0])
print('\nAbstract Encodings')
print(abstract_encodings)
print(tokenizer.convert_ids_to_tokens(abstract_encodings))


# Full Text
full_text_encodings = tokenizer.encode(ds['train']['fulltext'][0])
print('\nFull Text Encodings')
print(full_text_encodings)
print(tokenizer.convert_ids_to_tokens(full_text_encodings))

"""# Sentence BERT"""

!pip install -U sentence-transformers

"""https://www.sbert.net/docs/sentence_transformer/pretrained_models.html

https://github.com/UKPLab/sentence-transformers/tree/master/examples/training

https://arxiv.org/pdf/1908.10084

"""